global:
  imagePullPolicy: Always

pulsar:
  namespace: pulsar
  namespaceCreate: true
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    initialize: true
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    replicaCount: 1
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false
    
postgresql:
  namespaceOverride: postgresql
  auth:
    username: postgres
    password: postgres
    database: jobber

jobs:
  enabled: true
  replicas: 1
  image: '490004651582.dkr.ecr.us-east-1.amazonaws.com/jobber/jobs:latest'
  port: 3001

executor:
  enabled: true
  replicas: 1
  image: '490004651582.dkr.ecr.us-east-1.amazonaws.com/jobber/executor:latest'
  port: 3002

auth:
  enabled: true
  replicas: 1
  image: '490004651582.dkr.ecr.us-east-1.amazonaws.com/jobber/auth:latest'
  port: 
    http: 3000
    grpc: 5000
  jwt:
    secret: s490004651582
    expirationMs: 2880000