global:
  imagePullPolicy: Always

pulsar:
  namespace: pulsar
  namespaceCreate: true
  components:
    proxy: false
  zookeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  broker:
    replicaCount: 1
    podMonitor:
      enabled: false
  bookkeeper:
    replicaCount: 1
    podMonitor:
      enabled: false
  autorecovery:
    podMonitor:
      enabled: false
  proxy:
    podMonitor:
      enabled: false
  kube-prometheus-stack:
    enabled: false
    prometheusOperator:
      enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      enabled: false
    
postgresql:
  namespaceOverride: postgresql
  auth:
    username: postgres
    password: postgres
    database: jobber

jobs:
  enabled: true
  replicas: 1
  image: '490004651582.dkr.ecr.us-east-1.amazonaws.com/jobber/jobs:latest'
  port: 3001